[Networks]
  "base" = "https://base-rpc.publicnode.com"
  "base/sepolia" = "https://base-sepolia-rpc.publicnode.com"
  "bitcoin" = "https://bitcoin-rpc.publicnode.com"
  "bitcoin/testnet" = "https://bitcoin-testnet-rpc.publicnode.com"
  "bsc" = "https://bsc-rpc.publicnode.com"
  "bsc/testnet" = "https://bsc-testnet-rpc.publicnode.com"
  "ethereum" = "https://ethereum-rpc.publicnode.com"
  "ethereum/sepolia" = "https://ethereum-sepolia-rpc.publicnode.com"
  "mina" = "https://proxy.minaexplorer.com/graphql"
  "mina/devnet" = "https://api.minascan.io/node/devnet/v1/graphql"
  "polygon" = "https://polygon-bor-rpc.publicnode.com"
  "polygon/amoy" = "https://polygon-amoy-bor-rpc.publicnode.com"
  "secret" = "https://rpc.mainnet.secretsaturn.net"
  "secret/testnet" = "https://pulsar.rpc.secretnodes.com"
  "solana" = "https://solana-rpc.publicnode.com"
  "solana/devnet" = "https://api.devnet.solana.com"
  "xdc" = "https://erpc.xinfin.network"
  "xdc/apothem" = "https://earpc.apothem.network"
